<a href="https://colab.research.google.com/github/bishwajit02/Pytorch-Tutorial-Youtube/blob/main/Tensor_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensor Operations**

In [1]:
import torch

In [9]:
new_tensor = torch.arange(20)
new_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

#### To reshape a tensor, the divisions should be eqaul of the factors of range

In [19]:
# If the total numebr is unknown, -1 can be used, but the first number needs to be a valid factor of the inital range
new_tensor = new_tensor.reshape(-1,5)
new_tensor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [29]:
tensor2 = torch.arange(10)
tensor3 = tensor2.reshape(2,5)
tensor3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
tensor2[2] = 212

In [32]:
tensor2

tensor([  0,   1, 212,   3,   4,   5,   6,   7,   8,   9])

In [33]:
tensor3

tensor([[  0,   1, 212,   3,   4],
        [  5,   6,   7,   8,   9]])