<a href="https://colab.research.google.com/github/bishwajit02/Pytorch-Tutorial-Youtube/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensor**

In [1]:
import torch
import numpy as np

In [4]:
np1 = np.random.rand(3,4,5)
np1

array([[[0.08744148, 0.1109095 , 0.50839232, 0.16593245, 0.05359664],
        [0.98703415, 0.57806522, 0.52722445, 0.49620354, 0.37613058],
        [0.95059724, 0.09765012, 0.66717912, 0.57187812, 0.44719361],
        [0.34874835, 0.31872815, 0.10811862, 0.411033  , 0.39797677]],

       [[0.80475156, 0.74336922, 0.31679612, 0.9128753 , 0.50405964],
        [0.53914303, 0.56440692, 0.42149287, 0.76194152, 0.31440325],
        [0.48658804, 0.06569707, 0.71370248, 0.93274909, 0.46836042],
        [0.24843321, 0.83761835, 0.69795374, 0.53911519, 0.4794341 ]],

       [[0.63168966, 0.6779718 , 0.19312025, 0.79684089, 0.64139896],
        [0.97538577, 0.35562358, 0.22056934, 0.25303895, 0.77538835],
        [0.55040885, 0.56103272, 0.68924223, 0.12996115, 0.10512999],
        [0.00538869, 0.81577911, 0.81959394, 0.68030789, 0.17197187]]])

In [3]:
np1.dtype

dtype('float64')

In [8]:
tensor_2d = torch.randn(3,4,5)
tensor_2d

tensor([[[ 1.0221, -0.6424,  0.4496, -1.1396,  1.8124],
         [ 1.3997,  1.5090,  0.7619,  0.3221, -1.4806],
         [ 0.0085,  2.2789, -0.6026, -0.0184, -0.6549],
         [ 0.3931, -1.2968,  0.5226, -0.3126, -0.0558]],

        [[ 0.3193,  0.5907, -0.3710,  1.0568, -0.7180],
         [ 0.6231, -0.1395, -0.1498, -2.3932, -2.0076],
         [-0.1889, -0.8606, -1.6165,  0.4459, -0.5549],
         [ 1.5400,  0.6593,  0.7858,  1.3765, -0.6982]],

        [[-1.6242,  1.3453, -0.6740, -1.0915,  0.5703],
         [-0.0855, -1.1868,  0.0432,  0.9371,  0.7018],
         [-0.1977, -2.3132,  0.5804,  1.4561,  0.3849],
         [ 2.6809, -0.3117,  0.5387, -1.5945,  0.2242]]])

In [20]:
tnesor_3d = torch.zeros(1,1,5)
tnesor_3d
tensor_2d.dtype

torch.float32

### Creating tensor from numpy array


In [18]:
new = torch.tensor(np1)
new

tensor([[[0.0874, 0.1109, 0.5084, 0.1659, 0.0536],
         [0.9870, 0.5781, 0.5272, 0.4962, 0.3761],
         [0.9506, 0.0977, 0.6672, 0.5719, 0.4472],
         [0.3487, 0.3187, 0.1081, 0.4110, 0.3980]],

        [[0.8048, 0.7434, 0.3168, 0.9129, 0.5041],
         [0.5391, 0.5644, 0.4215, 0.7619, 0.3144],
         [0.4866, 0.0657, 0.7137, 0.9327, 0.4684],
         [0.2484, 0.8376, 0.6980, 0.5391, 0.4794]],

        [[0.6317, 0.6780, 0.1931, 0.7968, 0.6414],
         [0.9754, 0.3556, 0.2206, 0.2530, 0.7754],
         [0.5504, 0.5610, 0.6892, 0.1300, 0.1051],
         [0.0054, 0.8158, 0.8196, 0.6803, 0.1720]]], dtype=torch.float64)

In [19]:
new.dtype

torch.float64