<a href="https://colab.research.google.com/github/bishwajit02/Pytorch-Tutorial-Youtube/blob/main/Tensor_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensor Operations**

In [1]:
import torch

In [2]:
new_tensor = torch.arange(20)
new_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

#### To reshape a tensor, the divisions should be eqaul of the factors of range

In [3]:
# If the total numebr is unknown, -1 can be used, but the first number needs to be a valid factor of the inital range
new_tensor = new_tensor.reshape(-1,5)
new_tensor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [4]:
tensor2 = torch.arange(10)
tensor3 = tensor2.reshape(2,5)
tensor3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
tensor2[2] = 212

In [6]:
tensor2

tensor([  0,   1, 212,   3,   4,   5,   6,   7,   8,   9])

In [7]:
tensor3

tensor([[  0,   1, 212,   3,   4],
        [  5,   6,   7,   8,   9]])

In [8]:
# Grab a piece
ten = torch.arange(10)
ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
ten[7]

tensor(7)

In [10]:
ten1 = ten.reshape(5,2)
ten1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
# Slices
ten1[:,1]

tensor([1, 3, 5, 7, 9])

In [12]:
ten2 = ten.reshape(2,5)
ten2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
ten2[:,4:]

tensor([[4],
        [9]])